### ISSUE TITLE
How to compile it in android studio?

### ISSUE THREAD

**Issue by kolanski** [muziyongshixin/ORB-SLAM2-based-AR-on-Android#1]
I get opencv2/core/core.hpp: No such file or directory error for dbow

**Comment by unaplugin** [comment]
Hi, @muziyongshixin  In my Android Studio, it is built failed with errors like:
```
../../../../src/main/cpp\Eigen/Core:84:20: error: expected value in expression
#if EIGEN_COMP_MSVC
                                      ^
```
Do you know how to deal with it? Thx in advance.

**Comment by lldavuull** [comment]
opencv2 is not included in the code.
you can download opencv-3.2.0-android-sdk.zip
https://sourceforge.net/projects/opencvlibrary/files/opencv-android/3.2.0/

put the folder (opencv2 folder)
OpenCV-android-sdk\sdk\native\jni\include
into
app\src\main\cpp

**Comment by NCHUPJ** [comment]
> opencv2 is not included in the code.
> you can download opencv-3.2.0-android-sdk.zip
> https://sourceforge.net/projects/opencvlibrary/files/opencv-android/3.2.0/
> 
> put the folder (opencv2 folder)
> OpenCV-android-sdk\sdk\native\jni\include
> into
> app\src\main\cpp
Did you install OpenCV4Androi？
